# Use an official Node.js runtime as a parent image
FROM node:16-alpine

# Set the working directory to /netstager_client
WORKDIR /client

# Copy the package.json and yarn.lock files to the container
COPY package.json yarn.lock ./

# Install dependencies using Yarn
RUN yarn install

# Copy the rest of the application code to the container
COPY . .

EXPOSE 8080

# Start the application using Yarn
CMD ["yarn", "run" , "dev"]
