version: 3.8'
services:
  client:
    image: client-dev-i
    build:
      dockerfile: Dockerfile.dev
    container_name: client-dev-c
    volumes:
      - ./client:/client
      - node_modules:/client/node_modules/
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
  server:
    image: server-dev-i
    build:
      dockerfile: Dockerfile.server.dev
    container_name: server-dev-c
    volumes:
      - ./server:/server
      - node_modules:/server/node_modules/
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
volumes:
  node_modules: